jobscheduler:
  build: .
  # image: spagettys/jobscheduler-docker:latest
  links:
    - db:mysql
  volumes_from:
    - datastore
  ports:
    - '4446:4446'
    - '40444:40444'
db:
  image: mariadb:10.1.21
  ports:
    - '3306:3306'
  environment:
    MYSQL_USER: jobscheduler
    MYSQL_PASSWORD: jobscheduler
    MYSQL_ROOT_PASSWORD: scheduler
    MYSQL_DATABASE: jobscheduler

datastore:
  image: busybox
  command: /bin/true
  volumes:
    - /var/lib/mysql
    - ./live:/opt/jobscheduler/data/scheduler/config/live

js_agent:
  image: js_agent
